# Portugal Real Estate Market Analysis: Data Exploration and Cleaning

Graded Challenge 4

Name  : Narda Parama Agung Noviantoro

Batch : CODA-RMT-0023

This .ipynb file is used to conduct the data exploration and cleaning procedures on P1G4-Narda_Noviantoro_raw_portugal_listinigs to ensure a smooth analysis process on spreadsheets later on.

## Data Exploration

The syntax below is used to import pandas library into this session and to load the raw data file into a DataFrame (df).

Note: we use low_memory=False to avoid mixed data types warning which happens in larger datasets like this one.

Additionally, based on df.shape, the dataset consists of 184,332 rows and 23 columns.

In [4]:
import pandas as pd

df = pd.read_csv('P1G4-Narda_Noviantoro_raw_portugal_listings.csv', low_memory=False)

df.shape

(184332, 23)

The syntax below is used to see the first 50 rows of the dataset, to understand the general visual structure of the dataset.

In [5]:
df.head(50)

,Price,District,City,Town,Type,EnergyCertificate,TotalArea,NumberOfBathrooms,Parking,Floor,...,Garage,Elevator,ElectricCarsCharging,TotalRooms,NumberOfBedrooms,NumberOfWC,ConservationStatus,LivingArea,LotSize,BuiltArea
0,780000.0,Vila Real,Valpaços,Carrazedo de Montenegro e Curros,Farm,NC,552450.0,0.0,0.0,NaN,...,NaN,False,NaN,NaN,NaN,NaN,NaN,120.0,NaN,200.0
1,228000.0,Faro,São Brás de Alportel,São Brás de Alportel,Apartment,A+,108.0,2.0,1.0,Ground Floor,...,NaN,True,NaN,2.0,NaN,NaN,NaN,108.0,NaN,NaN
2,250000.0,Faro,São Brás de Alportel,São Brás de Alportel,Apartment,A+,114.0,0.0,1.0,1st Floor,...,NaN,True,NaN,2.0,NaN,NaN,NaN,114.0,NaN,NaN
3,250000.0,Faro,São Brás de Alportel,São Brás de Alportel,Apartment,A+,114.0,2.0,1.0,2nd Floor,...,NaN,True,NaN,2.0,NaN,NaN,NaN,114.0,NaN,NaN
4,158000.0,Faro,Portimão,Portimão,Apartment,D,21953.0,2.0,1.0,2nd Floor,...,NaN,True,NaN,1.0,NaN,NaN,NaN,42.0,NaN,48.0
5,250000.0,Faro,Loulé,São Clemente,Apartment,C,85.0,1.0,0.0,Ground Floor,...,NaN,True,NaN,2.0,NaN,NaN,NaN,85.0,NaN,96.0
6,435000.0,Faro,Loulé,São Clemente,House,D,226.0,2.0,2.0,Ground Floor,...,NaN,False,NaN,3.0,NaN,NaN,NaN,184.0,NaN,NaN
7,605000.0,Faro,Albufeira,Albufeira e Olhos de Água,House,C,640.0,3.0,2.0,NaN,...,NaN,False,NaN,3.0,NaN,NaN,NaN,113.0,NaN,113.0
8,320000.0,Faro,Albufeira,Albufeira e Olhos de Água,Store,C,69.0,0.0,0.0,NaN,...,NaN,False,NaN,NaN,NaN,NaN,NaN,69.0,NaN,159.0
9,185000.0,Faro,Loulé,Quarteira,Apartment,D,38.0,1.0,0.0,Above 10th Floor,...,NaN,True,NaN,0.0,NaN,NaN,NaN,38.0,NaN,48.0
10,340000.0,Faro,Albufeira,Albufeira e Olhos de Água,Apartment,D,91.0,2.0,0.0,Ground Floor,...,NaN,False,NaN,3.0,NaN,NaN,NaN,85.0,NaN,NaN
11,1500000.0,Faro,Faro,Faro (Sé e São Pedro),Apartment,A,421.0,NaN,3.0,5th Floor,...,NaN,True,NaN,7.0,NaN,NaN,NaN,262.0,NaN,313.0
12,185000.0,Faro,Portimão,Portimão,Apartment,D,38.0,1.0,0.0,Above 10th Floor,...,NaN,True,NaN,0.0,NaN,NaN,NaN,34.0,NaN,NaN
13,495000.0,Faro,Loulé,Quarteira,Apartment,C,139.0,2.0,1.0,1st Floor,...,NaN,False,NaN,2.0,NaN,NaN,NaN,139.0,NaN,NaN
14,279900.0,Faro,Faro,Faro (Sé e São Pedro),Apartment,D,90.0,2.0,0.0,Ground Floor,...,NaN,True,NaN,3.0,NaN,NaN,NaN,90.0,NaN,NaN
15,19000.0,Faro,Lagoa (Algarve),Estômbar e Parchal,Land,NC,3710.0,0.0,0.0,NaN,...,NaN,False,NaN,NaN,NaN,NaN,NaN,3710.0,NaN,3710.0
16,223000.0,Faro,São Brás de Alportel,São Brás de Alportel,Apartment,A+,81.0,2.0,1.0,Ground Floor,...,NaN,True,NaN,2.0,NaN,NaN,NaN,81.0,NaN,NaN
17,250000.0,Faro,São Brás de Alportel,São Brás de Alportel,Apartment,A+,115.0,2.0,1.0,1st Floor,...,NaN,True,NaN,2.0,NaN,NaN,NaN,115.0,NaN,NaN
18,2950000.0,Faro,Albufeira,Albufeira e Olhos de Água,Building,NC,265.0,0.0,0.0,NaN,...,NaN,False,NaN,NaN,NaN,NaN,NaN,406.0,NaN,465.0
19,165000.0,Faro,Castro Marim,Altura,Land,NC,960.0,0.0,3.0,NaN,...,NaN,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,9500.0,Faro,Albufeira,Albufeira e Olhos de Água,Apartment,NC,27.0,1.0,0.0,1st Floor,...,NaN,True,NaN,0.0,NaN,NaN,NaN,27.0,NaN,NaN
21,75000.0,Faro,Olhão,Moncarapacho e Fuseta,Land,NC,760.0,0.0,0.0,NaN,...,NaN,False,NaN,NaN,NaN,NaN,NaN,760.0,NaN,NaN
22,350000.0,Faro,Portimão,Portimão,Apartment,C,68.0,1.0,0.0,4th Floor,...,NaN,True,NaN,2.0,NaN,NaN,NaN,68.0,NaN,NaN
23,620000.0,Faro,Lagos,São Gonçalo de Lagos,Apartment,A,94.0,2.0,1.0,2nd Floor,...,NaN,True,NaN,2.0,NaN,NaN,NaN,74.0,NaN,116.0
24,159900.0,Faro,Portimão,Portimão,Apartment,D,55.0,1.0,0.0,3rd Floor,...,NaN,True,NaN,1.0,NaN,NaN,NaN,50.0,NaN,55.0
25,195000.0,Faro,Vila do Bispo,Vila do Bispo e Raposeira,House,NC,137.0,0.0,0.0,NaN,...,NaN,False,NaN,0.0,NaN,NaN,NaN,110.0,NaN,110.0
26,235000.0,Faro,Faro,Faro (Sé e São Pedro),House,NC,63.0,2.0,0.0,NaN,...,NaN,False,NaN,1.0,NaN,NaN,NaN,63.0,NaN,NaN
27,335000.0,Faro,Albufeira,Albufeira e Olhos de Água,Apartment,NC,574.0,2.0,0.0,Ground Floor,...,NaN,False,NaN,2.0,NaN,NaN,NaN,86.0,NaN,NaN
28,210000.0,Faro,Faro,Conceição e Estoi,Farm,NC,4600.0,0.0,3.0,NaN,...,NaN,False,NaN,5.0,NaN,NaN,NaN,177.0,NaN,177.0
29,585000.0,Faro,Lagos,São Gonçalo de Lagos,Apartment,A,94.0,2.0,1.0,Ground Floor,...,NaN,True,NaN,2.0,NaN,NaN,NaN,74.0,NaN,117.0
30,565000.0,Faro,Lagos,São Gonçalo de Lagos,Apartment,A,90.0,2.0,1.0,Ground Floor,...,NaN,True,NaN,2.0,NaN,NaN,NaN,72.0,NaN,97.0
31,320000.0,Faro,Loulé,São Sebastião,Apartment,A,308.0,2.0,1.0,1st Floor,...,NaN,True,NaN,2.0,NaN,NaN,NaN,77.0,NaN,95.0
32,340000.0,Faro,Loulé,São Sebastião,Apartment,A,94.0,2.0,1.0,3rd Floor,...,NaN,True,NaN,2.0,NaN,NaN,NaN,75.0,NaN,110.0
33,291000.0,Faro,Albufeira,Albufeira e Olhos de Água,Apartment,B,10560.0,1.0,1.0,1st Floor,...,NaN,True,NaN,1.0,NaN,NaN,NaN,50.0,NaN,67.0
34,175000.0,Faro,Faro,Faro (Sé e São Pedro),House,NC,78.0,2.0,0.0,NaN,...,NaN,False,NaN,4.0,NaN,NaN,NaN,78.0,NaN,NaN
35,600000.0,Faro,Lagos,São Gonçalo de Lagos,Apartment,A,97.0,2.0,1.0,1st Floor,...,NaN,True,NaN,1.0,NaN,NaN,NaN,79.0,NaN,118.0
36,1485000.0,Faro,Loulé,Quarteira,House,D,472.0,5.0,2.0,Ground Floor,...,NaN,False,NaN,4.0,NaN,NaN,NaN,414.0,NaN,NaN
37,125000.0,Faro,Portimão,Portimão,Other - Residential,NC,55.0,1.0,2.0,Ground Floor,...,NaN,True,NaN,2.0,NaN,NaN,NaN,55.0,NaN,NaN
38,25000.0,Faro,Portimão,Portimão,Garage,NC,15.0,0.0,1.0,Basement Level,...,NaN,True,NaN,0.0,NaN,NaN,NaN,15.0,NaN,NaN
39,360000.0,Faro,Loulé,Quarteira,Apartment,C,72.0,1.0,1.0,1st Floor,...,NaN,True,NaN,1.0,NaN,NaN,NaN,72.0,NaN,NaN
40,260000.0,Faro,Lagos,São Gonçalo de Lagos,Apartment,C,105.0,2.0,0.0,2nd Floor,...,NaN,False,NaN,2.0,NaN,NaN,NaN,105.0,NaN,114.0
41,100000.0,Faro,Alcoutim,Alcoutim e Pereiro,Land,NC,24920.0,0.0,0.0,NaN,...,NaN,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
42,420000.0,Faro,Portimão,Alvor,House,D,140.0,5.0,1.0,NaN,...,NaN,False,NaN,6.0,NaN,NaN,NaN,158.0,NaN,185.0
43,469000.0,Faro,Loulé,São Clemente,Building,E,203.0,0.0,2.0,NaN,...,NaN,False,NaN,NaN,NaN,NaN,NaN,258.0,NaN,NaN
44,330000.0,Faro,Loulé,São Sebastião,Apartment,A,308.0,2.0,1.0,2nd Floor,...,NaN,True,NaN,2.0,NaN,NaN,NaN,77.0,NaN,95.0
45,147000.0,Faro,Vila Real de Santo António,Vila Real de Santo António,Apartment,C,148.0,1.0,0.0,1st Floor,...,NaN,False,NaN,1.0,NaN,NaN,NaN,42.0,NaN,NaN
46,150000.0,Faro,Faro,Faro (Sé e São Pedro),Store,B,100.0,1.0,0.0,Ground Floor,...,NaN,False,NaN,NaN,NaN,NaN,NaN,228.0,NaN,228.0
47,272000.0,Faro,Albufeira,Albufeira e Olhos de Água,Apartment,A,10560.0,1.0,1.0,1st Floor,...,NaN,True,NaN,1.0,NaN,NaN,NaN,49.0,NaN,67.0
48,580000.0,Faro,Vila do Bispo,Budens,Apartment,D,84.0,2.0,1.0,3rd Floor,...,NaN,False,NaN,2.0,NaN,NaN,NaN,84.0,NaN,NaN
49,615000.0,Faro,Loulé,São Clemente,Apartment,D,218.0,3.0,2.0,3rd Floor,...,NaN,True,NaN,4.0,NaN,NaN,NaN,218.0,NaN,338.0

The below syntax is used to understand the raw dataset's overall structure for each column, including its Data Types and Non-Null counts.

Based on df.info(), the following can be confirmed:

- Only columns 'District' and 'City' have full data (184,332 non-null). Other columns have missing values to a certain extent.
- Columns that have minimal missing values include: 'Price', 'Town', 'Type', 'EnergyCertificate', 'TotalArea', 'NumberOfBathrooms', 'Parking', 'Elevator'.
- Other than these columns, the remainders have considerable to large amounts of missing values.
- For data types, there are 11 'float64' columns, 9 'str' columns, and 3 'object' columns.
    - Overall, the data types for each column are already in accordance with the column name and its values.
    - The three columns with 'object' as its data type also still make sense, this is because despite its values being True/False, pandas cannot treat this as true boolean due to missing values mixed in as well.
    - There is one exception, this being the column 'PublishDate' where values are 'str' and not in 'datetime[ns/us]'. This is worth flagging, but will not be converted during the data cleaning process, as it is part of a set of columns/metrics that will not be included in the analysis later on (thus will be dropped instead).

In [6]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 184332 entries, 0 to 184331
Data columns (total 23 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   Price                  183874 non-null  float64
 1   District               184332 non-null  str
 2   City                   184332 non-null  str
 3   Town                   184330 non-null  str
 4   Type                   184316 non-null  str
 5   EnergyCertificate      184318 non-null  str
 6   TotalArea              168792 non-null  float64
 7   NumberOfBathrooms      166962 non-null  float64
 8   Parking                184300 non-null  float64
 9   Floor                  27929 non-null   str
 10  ConstructionYear       121555 non-null  float64
 11  EnergyEfficiencyLevel  116085 non-null  str
 12  PublishDate            76508 non-null   str
 13  Garage                 116085 non-null  object
 14  Elevator               184300 non-null  object
 15  ElectricCarsCharging   116085 non-null  object
 16  TotalRooms             89597 non-null   float64
 17  NumberOfBedrooms       82357 non-null   float64
 18  NumberOfWC             75785 non-null   float64
 19  ConservationStatus     31172 non-null   str
 20  LivingArea             143232 non-null  float64
 21  LotSize                63605 non-null   float64
 22  BuiltArea              73508 non-null   float64
dtypes: float64(11), object(3), str(9)
memory usage: 32.3+ MB

The following syntax is used to further review the exact number of missing values are in different columns.

based on df.isnull().sum(), the following can be confirmed:
- Columns 'District' and 'City' has no missing values.
- There are 8 columns that has missing values of >90,000, which we can categorize it as Large, this includes: 'Floor', 'ConservationStatus', 'LotSize', 'BuiltArea', 'NumberOfWC', 'PublishDate', 'NumberOfBedrooms', and 'TotalRooms'.
- There are 5 columns that has missing values of >40,000 and <90,000, which we can categorize as Medium, this includes: 'Garage', 'ElectricCarCharging', 'EnergyEficiencyLevel', 'ConstructionYear', and 'LivingArea'.
- There are 3 columns that has missing values of >400 and <40,000, which we can categorise as Small, this includes: 'NumberOfBathrooms', 'TotalArea', and 'Price'.
- The remainder columns have very minimal values (<40), which includes: 'Elevator', 'Parking', 'Type', 'EnergyCertificate', and 'Town'.

In [7]:
df.isnull().sum()

Price                       458
District                      0
City                          0
Town                          2
Type                         16
EnergyCertificate            14
TotalArea                 15540
NumberOfBathrooms         17370
Parking                      32
Floor                    156403
ConstructionYear          62777
EnergyEfficiencyLevel     68247
PublishDate              107824
Garage                    68247
Elevator                     32
ElectricCarsCharging      68247
TotalRooms                94735
NumberOfBedrooms         101975
NumberOfWC               108547
ConservationStatus       153160
LivingArea                41100
LotSize                  120727
BuiltArea                110824
dtype: int64

Overall, based on df.info() and df.isnull().sum(), only 8 columns/metrics were suitable for the analysis and to answer the problem statement and its seven key questions.

Chosen Columns:
1. 'Price': was selected due to it being the primary metric to analyze property sales growth
2. 'District': was selected as it will become the basis for regional grouping when analysing price differentiation between regions. 'District' was chosen over 'City' and 'Town' due to its more generalized grouping, which makes results more reliable (calculating price averages and variation) and much easier to read when displayed with a chart.
3. 'Type': was selected as it will be used to analyze the effect of property types on selling price.
4. 'TotalArea': was selected as it will be used to analyze the effect of property size on selling price and to calculate price per m^2. Chosen over 'LivingArea' and 'BuiltArea' due to it having more complete data.
5. 'Parking', 'Elevator', and 'NumberOfBathrooms': were selected as they will be used to analyze the effect of facilities availability on selling price.
6. 'EnergyCertificate': was selected as it will be used to analyze the effect of energy efficiency on selling price. This was chosen over 'EnergyEfficiencyLevel' as it has more complete data.

Columns that will be dropped:
1. 'Floor', 'ConservationStatus', 'LotSize', 'BuiltArea', 'NumberOfBedrooms', 'NumberOfWC', 'PublishDate', 'TotalRooms', 'Garage', 'ElectricCarsCharging', 'EnergyEfficiencyLevel', 'ConstructionYear', and 'LivingArea': despite some columns still having relevance in the analysis, they will all still be dropped as they have too many missing values, which can make the analysis representing only a small fraction of the data, thus less reliable results.
2. 'City' and 'Town': will be dropped as they have smaller groupings compared to 'District', meaning smaller amounts of data per group, which may result in less reliable results when calculating price averages and variations.

The below syntax is used to check the total count of duplicated rows in the raw dataset. There is a total of 10,996 duplicate rows that needs to be removed.

In [8]:
df.duplicated().sum()

np.int64(10996)

The below syntax is used to create a statistics summary of the numerical columns/metrics that will be used in the analysis. This is done to check whether there are values that don't add up.

Based on .describe():
- 'Price': has a minimum value of just €1 and a maximum value of €2,000,000,000, which is much higher than the third quartil, this price range may not be realistic.
- 'TotalArea': has a minimum negative value of -7,196,067 and a maximum of 61,420,070,000, which the negative value alone would not make sense in this metric.
- 'NumberOfBathrooms': has a minimum negative value of -13 and a maximum value of 3,020, again the negative value alone does not make sense in this metric.
- 'Parking': range values are between 0 and 3, has no problems.

In [9]:
df[['Price', 'TotalArea', 'NumberOfBathrooms', 'Parking']].describe()

              Price     TotalArea  NumberOfBathrooms        Parking
count  1.838740e+05  1.687920e+05       166962.00000  184300.000000
mean   4.002180e+05  3.877752e+05            1.69054       0.493082
std    5.702520e+06  1.495398e+08            7.58936       0.765127
min    1.000000e+00 -7.196067e+06          -13.00000       0.000000
25%    9.250000e+04  8.800000e+01            0.00000       0.000000
50%    2.375000e+05  1.420000e+02            1.00000       0.000000
75%    4.210000e+05  3.550000e+02            2.00000       1.000000
max    2.000000e+09  6.142007e+10         3020.00000       3.000000

The following syntaxes is used to check whether the categorical columns have any inconsistencies in their values.

After searching, 'Z - Fora de Portugal' is not a district in Portugal:

In [10]:
df['District'].value_counts()

District
Lisboa                  44098
Porto                   30995
Setúbal                 16162
Braga                   15149
Faro                    12026
Coimbra                 10437
Aveiro                  10119
Leiria                   9802
Santarém                 9713
Castelo Branco           6459
Viana do Castelo         4685
Évora                    3159
Vila Real                2910
Portalegre               2556
Guarda                   2110
Beja                     1844
Bragança                 1506
Ilha de Santa Maria       275
Viseu                      71
Ilha de São Miguel         66
Ilha Terceira              58
Ilha de Porto Santo        57
Z - Fora de Portugal       44
Ilha da Madeira            22
Ilha do Faial               5
Ilha de São Jorge           2
Ilha das Flores             1
Ilha do Pico                1
Name: count, dtype: int64

We can assume NC, No Certificate, and Not available to mean the same.

In [11]:
df['EnergyCertificate'].value_counts()

EnergyCertificate
NC                80268
C                 22658
D                 21515
A                 15022
E                 14716
F                 10025
A+                 7341
B-                 6317
B                  5851
G                   542
No Certificate       45
Not available        18
Name: count, dtype: int64

There are no inconsistencies in the column 'Type':

In [12]:
df['Type'].value_counts()

Type
Apartment              67415
House                  50221
Land                   41018
Store                   6794
Farm                    4987
Building                3321
Transfer of lease       2379
Warehouse               1937
Garage                  1339
Other - Commercial      1048
Office                   896
Other - Residential      820
Duplex                   547
Industrial               533
Investment               311
Storage                  283
Hotel                    206
Studio                   102
Estate                    86
Mansion                   55
Manor                     18
Name: count, dtype: int64

There are no inconsistencies in the column 'Parking':

In [13]:
df['Parking'].value_counts()

Parking
0.0    117056
1.0     50895
2.0      9067
3.0      7282
Name: count, dtype: int64

There are no inconsistencies in the column 'Elevator':

In [14]:
df['Elevator'].value_counts()

Elevator
False    137678
True      46622
Name: count, dtype: int64

## Data Cleaning

The following syntax is done to do an initial duplicate deletion on the entire raw dataset saved in 'df_delduplicate' (to ensure the original df is not touched).

This deletion at 23 columns, rather than doing it on the selected 8 columns, was done to avoid the removal of valid listings. This is because rows that look similar on the 8 columns may still be different listings on the 23 columns. If we had done the duplicates deletion after selecting the 8 columns into a new dataframe, these listings would be deleted and cause unreliable results during the analysis.

In [15]:
df_delduplicate = df.drop_duplicates()
df_delduplicate.shape

(173336, 23)

The following syntax is to select the 8 columns that will be cleaned and used in the analysis later on, saving them into a variable named 'df_cleaned'.

As well as using .head(50) to show the first 50 rows of the df_cleaned.

In [16]:
df_cleaned = df_delduplicate[['Price', 'District', 'Type', 'TotalArea', 'Parking', 'Elevator', 'NumberOfBathrooms', 'EnergyCertificate']].copy()

df_cleaned.head(50)

,Price,District,Type,TotalArea,Parking,Elevator,NumberOfBathrooms,EnergyCertificate
0,780000.0,Vila Real,Farm,552450.0,0.0,False,0.0,NC
1,228000.0,Faro,Apartment,108.0,1.0,True,2.0,A+
2,250000.0,Faro,Apartment,114.0,1.0,True,0.0,A+
3,250000.0,Faro,Apartment,114.0,1.0,True,2.0,A+
4,158000.0,Faro,Apartment,21953.0,1.0,True,2.0,D
5,250000.0,Faro,Apartment,85.0,0.0,True,1.0,C
6,435000.0,Faro,House,226.0,2.0,False,2.0,D
7,605000.0,Faro,House,640.0,2.0,False,3.0,C
8,320000.0,Faro,Store,69.0,0.0,False,0.0,C
9,185000.0,Faro,Apartment,38.0,0.0,True,1.0,D
10,340000.0,Faro,Apartment,91.0,0.0,False,2.0,D
11,1500000.0,Faro,Apartment,421.0,3.0,True,NaN,A
12,185000.0,Faro,Apartment,38.0,0.0,True,1.0,D
13,495000.0,Faro,Apartment,139.0,1.0,False,2.0,C
14,279900.0,Faro,Apartment,90.0,0.0,True,2.0,D
15,19000.0,Faro,Land,3710.0,0.0,False,0.0,NC
16,223000.0,Faro,Apartment,81.0,1.0,True,2.0,A+
17,250000.0,Faro,Apartment,115.0,1.0,True,2.0,A+
18,2950000.0,Faro,Building,265.0,0.0,False,0.0,NC
19,165000.0,Faro,Land,960.0,3.0,False,0.0,NC
20,9500.0,Faro,Apartment,27.0,0.0,True,1.0,NC
21,75000.0,Faro,Land,760.0,0.0,False,0.0,NC
22,350000.0,Faro,Apartment,68.0,0.0,True,1.0,C
23,620000.0,Faro,Apartment,94.0,1.0,True,2.0,A
24,159900.0,Faro,Apartment,55.0,0.0,True,1.0,D
25,195000.0,Faro,House,137.0,0.0,False,0.0,NC
26,235000.0,Faro,House,63.0,0.0,False,2.0,NC
27,335000.0,Faro,Apartment,574.0,0.0,False,2.0,NC
28,210000.0,Faro,Farm,4600.0,3.0,False,0.0,NC
29,585000.0,Faro,Apartment,94.0,1.0,True,2.0,A
30,565000.0,Faro,Apartment,90.0,1.0,True,2.0,A
31,320000.0,Faro,Apartment,308.0,1.0,True,2.0,A
32,340000.0,Faro,Apartment,94.0,1.0,True,2.0,A
33,291000.0,Faro,Apartment,10560.0,1.0,True,1.0,B
34,175000.0,Faro,House,78.0,0.0,False,2.0,NC
35,600000.0,Faro,Apartment,97.0,1.0,True,2.0,A
36,1485000.0,Faro,House,472.0,2.0,False,5.0,D
37,125000.0,Faro,Other - Residential,55.0,2.0,True,1.0,NC
38,25000.0,Faro,Garage,15.0,1.0,True,0.0,NC
39,360000.0,Faro,Apartment,72.0,1.0,True,1.0,C
40,260000.0,Faro,Apartment,105.0,0.0,False,2.0,C
41,100000.0,Faro,Land,24920.0,0.0,False,0.0,NC
42,420000.0,Faro,House,140.0,1.0,False,5.0,D
43,469000.0,Faro,Building,203.0,2.0,False,0.0,E
44,330000.0,Faro,Apartment,308.0,1.0,True,2.0,A
45,147000.0,Faro,Apartment,148.0,0.0,False,1.0,C
46,150000.0,Faro,Store,100.0,0.0,False,1.0,B
47,272000.0,Faro,Apartment,10560.0,1.0,True,1.0,A
48,580000.0,Faro,Apartment,84.0,1.0,False,2.0,D
49,615000.0,Faro,Apartment,218.0,2.0,True,3.0,D

The following syntax is used to remove any rows that has missing values.

In [17]:
df_cleaned = df_cleaned.dropna()
df_cleaned.shape

(149721, 8)

The following syntax is used to remove rows with any values that do not make sense. This is done by setting judgement cut off values or filters to only include realistic values in the dataset, and saving them into df_cleaned.

NOTE: These values were derived from personal judgements of what is sensible in a property listing. The need for this came about when previous syntaxes showed that the distribution of data of columns 'Price', 'TotalArea', and 'NumberOfBathrooms' did not make sense.

In [18]:
df_cleaned = df_cleaned[df_cleaned['Price'] >= 1000]
df_cleaned = df_cleaned[df_cleaned['Price'] <= 60000000]

df_cleaned = df_cleaned[df_cleaned['TotalArea'] > 0]
df_cleaned = df_cleaned[df_cleaned['TotalArea'] <= 8000000]

df_cleaned = df_cleaned[df_cleaned['NumberOfBathrooms'] >= 0]
df_cleaned = df_cleaned[df_cleaned['NumberOfBathrooms'] <= 15]

df_cleaned.shape

(148619, 8)

The following syntax is used to remove rows with 'Z - Fora de Portugal' as a district.

In [19]:
df_cleaned = df_cleaned[df_cleaned['District'] != 'Z - Fora de Portugal']
df_cleaned['District'].value_counts()

District
Lisboa                 38127
Porto                  25745
Setúbal                13238
Braga                  11893
Faro                    9790
Coimbra                 8290
Aveiro                  7451
Santarém                7408
Leiria                  7361
Castelo Branco          4620
Viana do Castelo        3457
Évora                   2523
Vila Real               2201
Portalegre              2123
Guarda                  1572
Beja                    1476
Bragança                 906
Ilha de Santa Maria      211
Ilha de São Miguel        55
Viseu                     53
Ilha de Porto Santo       36
Ilha Terceira             36
Ilha da Madeira           15
Ilha do Faial              3
Ilha de São Jorge          1
Ilha das Flores            1
Ilha do Pico               1
Name: count, dtype: int64

The following syntax is used to combine 'NC', 'No Certificate', and 'Not available' as 'Not Certificated'.

In [20]:
df_cleaned['EnergyCertificate'] = df_cleaned['EnergyCertificate'].replace(['NC', 'No Certificate', 'Not available'], 'Not Certificated')
df_cleaned['EnergyCertificate'].value_counts()

EnergyCertificate
Not Certificated    52661
C                   20921
D                   20293
E                   13902
A                   13520
F                    9374
A+                   6421
B-                   5663
B                    5367
G                     471
Name: count, dtype: int64

The following syntaxes below are used for final verification before exporting clean data.

The below syntax is to check the structure of the clean data.

In [21]:
df_cleaned.shape

(148593, 8)

The below syntax is used to check whether there are any missing values in the clean data (confirmed none).

In [22]:
df_cleaned.isnull().sum()

Price                0
District             0
Type                 0
TotalArea            0
Parking              0
Elevator             0
NumberOfBathrooms    0
EnergyCertificate    0
dtype: int64

The below syntax is used to check whether the clean data has realistic numerical values (confirmed all sensible values).

In [23]:
df_cleaned.describe()

              Price     TotalArea        Parking  NumberOfBathrooms
count  1.485930e+05  1.485930e+05  148593.000000      148593.000000
mean   3.972257e+05  3.571835e+03       0.554212           1.737040
std    5.959378e+05  6.905804e+04       0.788948           1.534686
min    1.000000e+03  1.000000e+00       0.000000           0.000000
25%    1.300000e+05  8.800000e+01       0.000000           1.000000
50%    2.600000e+05  1.390000e+02       0.000000           2.000000
75%    4.450000e+05  3.270000e+02       1.000000           2.000000
max    2.000000e+07  5.912500e+06       3.000000          15.000000

The below syntax is used to save the cleaned dataset into a csv file.

In [24]:
df_cleaned.to_csv('P1G4-Narda_Noviantoro_clean_portugal_listings.csv', index=False)